// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.201 (2026-07-04). Re-scaffold when Claude Code is upgraded.
// Event: Elicitation. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface ElicitationInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Name of the MCP server requesting input. */
  mcpServerName: string;
  /** The prompt message from the MCP server. */
  message: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
  /** form for form-based elicitation, url for browser-based authentication. */
  mode?: "form" | "url";
  /** Authentication URL. Present for url-mode elicitation. */
  url?: string;
  /** Unique identifier for this elicitation request. */
  elicitationId?: string;
  /** JSON Schema object describing the form fields. Present for form-mode elicitation. */
  requestedSchema?: Record<string, unknown>;
}

export interface ElicitationHookSpecificOutput {
  hookEventName: "Elicitation";
  /** Whether to accept, decline, or cancel the request. */
  action: "accept" | "decline" | "cancel";
  /** Form field values to submit. Only used when action is accept. */
  content?: Record<string, unknown>;
}

export interface ElicitationOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  hookSpecificOutput?: ElicitationHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseElicitationInput(data: Record<string, any>): ElicitationInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    mcpServerName: data["mcp_server_name"],
    message: data["message"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
    mode: data["mode"] ?? undefined,
    url: data["url"] ?? undefined,
    elicitationId: data["elicitation_id"] ?? undefined,
    requestedSchema: data["requested_schema"] ?? undefined,
  };
}

export function parseElicitationHookSpecificOutput(data: Record<string, any>): ElicitationHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    action: data["action"],
    content: data["content"] ?? undefined,
  };
}

export function parseElicitationOutput(data: Record<string, any>): ElicitationOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parseElicitationHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeElicitationInput(obj: ElicitationInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["mcp_server_name"] = obj.mcpServerName;
  result["message"] = obj.message;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.mode !== undefined) {
    result["mode"] = obj.mode;
  }
  if (obj.url !== undefined) {
    result["url"] = obj.url;
  }
  if (obj.elicitationId !== undefined) {
    result["elicitation_id"] = obj.elicitationId;
  }
  if (obj.requestedSchema !== undefined) {
    result["requested_schema"] = obj.requestedSchema;
  }
  return result;
}

export function serializeElicitationHookSpecificOutput(obj: ElicitationHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  result["action"] = obj.action;
  if (obj.content !== undefined) {
    result["content"] = obj.content;
  }
  return result;
}

export function serializeElicitationOutput(obj: ElicitationOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializeElicitationHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: ElicitationInput) => ElicitationOutput | null): void {
  const event = parseElicitationInput(JSON.parse(readStdin()));
  // Blocking event. Set hookSpecificOutput.action to accept / decline / cancel.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeElicitationOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
