// Generated by cc-flyrig from the Claude Code statusline IR — do not edit.
// Source schema: cc-2.1.200 (2026-07-03). Re-scaffold when Claude Code is upgraded.
// Event: SubagentStatusLine. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

/** One entry of subagentStatusLine's tasks[]. */
export interface TaskInfo {
  id: string;
  /** Observed value: local_agent. */
  type: string;
  /** Observed value: running. */
  status: string;
  description: string;
  label: string;
  /** Epoch milliseconds. */
  startTime: number;
  tokenCount: number;
  tokenSamples: number[];
  cwd: string;
  /** Documented by the /statusline reference. */
  name?: string;
}

/** A small, fixed envelope — NOT a subset of StatusLineInput and NOT the hooks CommonInput envelope (no hook_event_name, no permission_mode). */
export interface SubagentStatusLineInput {
  sessionId: string;
  transcriptPath: string;
  cwd: string;
  promptId: string;
  columns: number;
  tasks: TaskInfo[];
}

/** One {id, content} row per visible subagent. Authored from the /statusline reference. */
export interface SubagentStatusLineOutput {
  /** Identifier of the subagent row this content replaces. */
  id: string;
  /** Text rendered for this subagent's row. */
  content: string;
}

export function parseTaskInfo(data: Record<string, any>): TaskInfo {
  return {
    id: data["id"],
    type: data["type"],
    status: data["status"],
    description: data["description"],
    label: data["label"],
    startTime: data["startTime"],
    tokenCount: data["tokenCount"],
    tokenSamples: data["tokenSamples"],
    cwd: data["cwd"],
    name: data["name"] ?? undefined,
  };
}

export function parseSubagentStatusLineInput(data: Record<string, any>): SubagentStatusLineInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    promptId: data["prompt_id"],
    columns: data["columns"],
    tasks: data["tasks"].map(parseTaskInfo),
  };
}

export function parseSubagentStatusLineOutput(data: Record<string, any>): SubagentStatusLineOutput {
  return {
    id: data["id"],
    content: data["content"],
  };
}

export function serializeTaskInfo(obj: TaskInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["id"] = obj.id;
  result["type"] = obj.type;
  result["status"] = obj.status;
  result["description"] = obj.description;
  result["label"] = obj.label;
  result["startTime"] = obj.startTime;
  result["tokenCount"] = obj.tokenCount;
  result["tokenSamples"] = obj.tokenSamples;
  result["cwd"] = obj.cwd;
  if (obj.name !== undefined) {
    result["name"] = obj.name;
  }
  return result;
}

export function serializeSubagentStatusLineInput(obj: SubagentStatusLineInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["prompt_id"] = obj.promptId;
  result["columns"] = obj.columns;
  result["tasks"] = obj.tasks.map(serializeTaskInfo);
  return result;
}

export function serializeSubagentStatusLineOutput(obj: SubagentStatusLineOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["id"] = obj.id;
  result["content"] = obj.content;
  return result;
}

export function run(handle: (event: SubagentStatusLineInput) => SubagentStatusLineOutput[]): void {
  const event = parseSubagentStatusLineInput(JSON.parse(readStdin()));
  // subagentStatusLine: one SubagentStatusLineOutput row per visible subagent, one JSON object per line.
  for (const row of handle(event)) {
    console.log(JSON.stringify(serializeSubagentStatusLineOutput(row)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
