# Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
# Source schema: cc-2.1.200 (2026-07-03). Re-scaffold when Claude Code is upgraded.
# Event: PostToolUse. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Literal


class EffortLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


@dataclass(slots=True)
class EffortObject:
    level: EffortLevel

    @classmethod
    def from_dict(cls, data: dict) -> "EffortObject":
        return cls(
            level=EffortLevel(data["level"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["level"] = self.level.value
        return result


class PermissionMode(str, Enum):
    DEFAULT = "default"
    PLAN = "plan"
    ACCEPT_EDITS = "acceptEdits"
    AUTO = "auto"
    DONT_ASK = "dontAsk"
    BYPASS_PERMISSIONS = "bypassPermissions"


@dataclass(slots=True)
class PostToolUseInput:
    session_id: str
    """Current session identifier."""
    transcript_path: str
    """Path to conversation JSON."""
    cwd: str
    """Current working directory when the hook is invoked."""
    hook_event_name: str
    """Name of the event that fired."""
    tool_name: str
    """Name of the tool that completed."""
    tool_input: dict
    """Arguments sent to the tool."""
    tool_response: dict | list[dict]
    """Result returned by the tool. Object for built-in tools; content-block array for MCP tools."""
    tool_use_id: str
    """Unique identifier for this tool call."""
    permission_mode: PermissionMode | None = None
    """Current permission mode. Not all events include this field."""
    effort: EffortObject | None = None
    """Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter."""
    agent_id: str | None = None
    """Unique identifier for the subagent. Present only when the hook fires inside a subagent call."""
    agent_type: str | None = None
    """Agent name. Present when the session uses --agent or the hook fires inside a subagent."""
    prompt_id: str | None = None
    """UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later."""
    duration_ms: float | None = None
    """Tool execution time in milliseconds. Excludes time in permission prompts and PreToolUse hooks."""

    @classmethod
    def from_dict(cls, data: dict) -> "PostToolUseInput":
        return cls(
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            cwd=data["cwd"],
            hook_event_name=data["hook_event_name"],
            tool_name=data["tool_name"],
            tool_input=data["tool_input"],
            tool_response=data["tool_response"],
            tool_use_id=data["tool_use_id"],
            permission_mode=PermissionMode(data["permission_mode"])
            if data.get("permission_mode") is not None
            else None,
            effort=EffortObject.from_dict(data["effort"]) if data.get("effort") is not None else None,
            agent_id=data.get("agent_id"),
            agent_type=data.get("agent_type"),
            prompt_id=data.get("prompt_id"),
            duration_ms=data.get("duration_ms"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["cwd"] = self.cwd
        result["hook_event_name"] = self.hook_event_name
        result["tool_name"] = self.tool_name
        result["tool_input"] = self.tool_input
        result["tool_response"] = self.tool_response
        result["tool_use_id"] = self.tool_use_id
        if self.permission_mode is not None:
            result["permission_mode"] = self.permission_mode.value
        if self.effort is not None:
            result["effort"] = self.effort.to_dict()
        if self.agent_id is not None:
            result["agent_id"] = self.agent_id
        if self.agent_type is not None:
            result["agent_type"] = self.agent_type
        if self.prompt_id is not None:
            result["prompt_id"] = self.prompt_id
        if self.duration_ms is not None:
            result["duration_ms"] = self.duration_ms
        return result


@dataclass(slots=True)
class PostToolUseHookSpecificOutput:
    hook_event_name: Literal["PostToolUse"]
    additional_context: str | None = None
    """String added to Claude's context alongside the tool result."""
    updated_tool_output: dict | None = None
    """Replaces the tool's output with the provided value before it is sent to Claude. Must match the tool's output shape."""
    updated_mcp_tool_output: dict | None = None
    """Replaces the output for MCP tools only. Prefer updatedToolOutput."""

    @classmethod
    def from_dict(cls, data: dict) -> "PostToolUseHookSpecificOutput":
        return cls(
            hook_event_name=data["hookEventName"],
            additional_context=data.get("additionalContext"),
            updated_tool_output=data.get("updatedToolOutput"),
            updated_mcp_tool_output=data.get("updatedMCPToolOutput"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["hookEventName"] = self.hook_event_name
        if self.additional_context is not None:
            result["additionalContext"] = self.additional_context
        if self.updated_tool_output is not None:
            result["updatedToolOutput"] = self.updated_tool_output
        if self.updated_mcp_tool_output is not None:
            result["updatedMCPToolOutput"] = self.updated_mcp_tool_output
        return result


@dataclass(slots=True)
class PostToolUseOutput:
    continue_: bool | None = None
    """If false, Claude stops processing entirely after the hook runs."""
    stop_reason: str | None = None
    """Message shown to the user when continue is false. Not shown to Claude."""
    suppress_output: bool | None = None
    """If true, hides the hook's stdout from the transcript."""
    system_message: str | None = None
    """Warning message shown to the user."""
    terminal_sequence: str | None = None
    """One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored."""
    decision: Literal["block"] | None = None
    """block adds the reason next to the tool result. Claude still sees the original output."""
    reason: str | None = None
    """Explanation shown to Claude when decision is block."""
    hook_specific_output: PostToolUseHookSpecificOutput | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "PostToolUseOutput":
        return cls(
            continue_=data.get("continue"),
            stop_reason=data.get("stopReason"),
            suppress_output=data.get("suppressOutput"),
            system_message=data.get("systemMessage"),
            terminal_sequence=data.get("terminalSequence"),
            decision=data.get("decision"),
            reason=data.get("reason"),
            hook_specific_output=PostToolUseHookSpecificOutput.from_dict(data["hookSpecificOutput"])
            if data.get("hookSpecificOutput") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        if self.continue_ is not None:
            result["continue"] = self.continue_
        if self.stop_reason is not None:
            result["stopReason"] = self.stop_reason
        if self.suppress_output is not None:
            result["suppressOutput"] = self.suppress_output
        if self.system_message is not None:
            result["systemMessage"] = self.system_message
        if self.terminal_sequence is not None:
            result["terminalSequence"] = self.terminal_sequence
        if self.decision is not None:
            result["decision"] = self.decision
        if self.reason is not None:
            result["reason"] = self.reason
        if self.hook_specific_output is not None:
            result["hookSpecificOutput"] = self.hook_specific_output.to_dict()
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = PostToolUseInput.from_dict(json.loads(sys.stdin.read()))
    # Blocking event. Set decision="block" and reason to stop the action. Returning None allows.
    decision = handle(event)
    if decision is not None:
        print(json.dumps(decision.to_dict()))
    return 0
