# Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
# Source schema: cc-2.1.185 (2026-06-20). Re-scaffold when Claude Code is upgraded.
# Event: PermissionRequest. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Literal


class EffortLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


@dataclass(slots=True)
class EffortObject:
    level: EffortLevel

    @classmethod
    def from_dict(cls, data: dict) -> "EffortObject":
        return cls(
            level=EffortLevel(data["level"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["level"] = self.level.value
        return result


class PermissionMode(str, Enum):
    DEFAULT = "default"
    PLAN = "plan"
    ACCEPT_EDITS = "acceptEdits"
    AUTO = "auto"
    DONT_ASK = "dontAsk"
    BYPASS_PERMISSIONS = "bypassPermissions"


@dataclass(slots=True)
class PermissionUpdateEntry:
    type: Literal["addRules", "replaceRules", "removeRules", "setMode", "addDirectories", "removeDirectories"]
    destination: Literal["session", "localSettings", "projectSettings", "userSettings"]
    rules: list[dict] | None = None
    """For addRules/replaceRules/removeRules."""
    behavior: Literal["allow", "deny", "ask"] | None = None
    """For addRules/replaceRules/removeRules."""
    mode: Literal["default", "auto", "acceptEdits", "dontAsk", "bypassPermissions", "plan"] | None = None
    """For setMode."""
    directories: list[str] | None = None
    """For addDirectories/removeDirectories."""

    @classmethod
    def from_dict(cls, data: dict) -> "PermissionUpdateEntry":
        return cls(
            type=data["type"],
            destination=data["destination"],
            rules=data.get("rules"),
            behavior=data.get("behavior"),
            mode=data.get("mode"),
            directories=data.get("directories"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["type"] = self.type
        result["destination"] = self.destination
        if self.rules is not None:
            result["rules"] = self.rules
        if self.behavior is not None:
            result["behavior"] = self.behavior
        if self.mode is not None:
            result["mode"] = self.mode
        if self.directories is not None:
            result["directories"] = self.directories
        return result


@dataclass(slots=True)
class PermissionRequestInput:
    session_id: str
    """Current session identifier."""
    transcript_path: str
    """Path to conversation JSON."""
    cwd: str
    """Current working directory when the hook is invoked."""
    hook_event_name: str
    """Name of the event that fired."""
    tool_name: str
    """Name of the tool requesting permission."""
    tool_input: dict
    """Tool input parameters. Shape depends on the tool."""
    permission_mode: PermissionMode | None = None
    """Current permission mode. Not all events include this field."""
    effort: EffortObject | None = None
    """Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter."""
    agent_id: str | None = None
    """Unique identifier for the subagent. Present only when the hook fires inside a subagent call."""
    agent_type: str | None = None
    """Agent name. Present when the session uses --agent or the hook fires inside a subagent."""
    permission_suggestions: list[PermissionUpdateEntry] | None = None
    """The always-allow options the user would normally see in the permission dialog."""

    @classmethod
    def from_dict(cls, data: dict) -> "PermissionRequestInput":
        return cls(
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            cwd=data["cwd"],
            hook_event_name=data["hook_event_name"],
            tool_name=data["tool_name"],
            tool_input=data["tool_input"],
            permission_mode=PermissionMode(data["permission_mode"])
            if data.get("permission_mode") is not None
            else None,
            effort=EffortObject.from_dict(data["effort"]) if data.get("effort") is not None else None,
            agent_id=data.get("agent_id"),
            agent_type=data.get("agent_type"),
            permission_suggestions=[PermissionUpdateEntry.from_dict(_v) for _v in data["permission_suggestions"]]
            if data.get("permission_suggestions") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["cwd"] = self.cwd
        result["hook_event_name"] = self.hook_event_name
        result["tool_name"] = self.tool_name
        result["tool_input"] = self.tool_input
        if self.permission_mode is not None:
            result["permission_mode"] = self.permission_mode.value
        if self.effort is not None:
            result["effort"] = self.effort.to_dict()
        if self.agent_id is not None:
            result["agent_id"] = self.agent_id
        if self.agent_type is not None:
            result["agent_type"] = self.agent_type
        if self.permission_suggestions is not None:
            result["permission_suggestions"] = [_v.to_dict() for _v in self.permission_suggestions]
        return result


@dataclass(slots=True)
class PermissionRequestHookSpecificDecision:
    behavior: Literal["allow", "deny"]
    """allow grants the permission, deny denies it."""
    updated_input: dict | None = None
    """For allow only: modifies the tool's input parameters before execution."""
    updated_permissions: list[PermissionUpdateEntry] | None = None
    """For allow only: permission update entries to apply."""
    message: str | None = None
    """For deny only: tells Claude why the permission was denied."""
    interrupt: bool | None = None
    """For deny only: if true, stops Claude."""

    @classmethod
    def from_dict(cls, data: dict) -> "PermissionRequestHookSpecificDecision":
        return cls(
            behavior=data["behavior"],
            updated_input=data.get("updatedInput"),
            updated_permissions=[PermissionUpdateEntry.from_dict(_v) for _v in data["updatedPermissions"]]
            if data.get("updatedPermissions") is not None
            else None,
            message=data.get("message"),
            interrupt=data.get("interrupt"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["behavior"] = self.behavior
        if self.updated_input is not None:
            result["updatedInput"] = self.updated_input
        if self.updated_permissions is not None:
            result["updatedPermissions"] = [_v.to_dict() for _v in self.updated_permissions]
        if self.message is not None:
            result["message"] = self.message
        if self.interrupt is not None:
            result["interrupt"] = self.interrupt
        return result


@dataclass(slots=True)
class PermissionRequestHookSpecificOutput:
    hook_event_name: Literal["PermissionRequest"]
    decision: PermissionRequestHookSpecificDecision | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "PermissionRequestHookSpecificOutput":
        return cls(
            hook_event_name=data["hookEventName"],
            decision=PermissionRequestHookSpecificDecision.from_dict(data["decision"])
            if data.get("decision") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["hookEventName"] = self.hook_event_name
        if self.decision is not None:
            result["decision"] = self.decision.to_dict()
        return result


@dataclass(slots=True)
class PermissionRequestOutput:
    continue_: bool | None = None
    """If false, Claude stops processing entirely after the hook runs."""
    stop_reason: str | None = None
    """Message shown to the user when continue is false. Not shown to Claude."""
    suppress_output: bool | None = None
    """If true, hides the hook's stdout from the transcript."""
    system_message: str | None = None
    """Warning message shown to the user."""
    terminal_sequence: str | None = None
    """One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored."""
    hook_specific_output: PermissionRequestHookSpecificOutput | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "PermissionRequestOutput":
        return cls(
            continue_=data.get("continue"),
            stop_reason=data.get("stopReason"),
            suppress_output=data.get("suppressOutput"),
            system_message=data.get("systemMessage"),
            terminal_sequence=data.get("terminalSequence"),
            hook_specific_output=PermissionRequestHookSpecificOutput.from_dict(data["hookSpecificOutput"])
            if data.get("hookSpecificOutput") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        if self.continue_ is not None:
            result["continue"] = self.continue_
        if self.stop_reason is not None:
            result["stopReason"] = self.stop_reason
        if self.suppress_output is not None:
            result["suppressOutput"] = self.suppress_output
        if self.system_message is not None:
            result["systemMessage"] = self.system_message
        if self.terminal_sequence is not None:
            result["terminalSequence"] = self.terminal_sequence
        if self.hook_specific_output is not None:
            result["hookSpecificOutput"] = self.hook_specific_output.to_dict()
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = PermissionRequestInput.from_dict(json.loads(sys.stdin.read()))
    # Blocking event. Set hook_specific_output.decision.behavior to "allow" or "deny".
    decision = handle(event)
    if decision is not None:
        print(json.dumps(decision.to_dict()))
    return 0
