# Generated by cc-flyrig from the Claude Code statusline IR — do not edit.
# Source schema: cc-2.1.198 (2026-07-02). Re-scaffold when Claude Code is upgraded.
# Event: StatusLine. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass
from enum import Enum


@dataclass(slots=True)
class AgentInfo:
    name: str

    @classmethod
    def from_dict(cls, data: dict) -> "AgentInfo":
        return cls(
            name=data["name"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = self.name
        return result


@dataclass(slots=True)
class CurrentUsage:
    input_tokens: int
    output_tokens: int
    cache_creation_input_tokens: int
    cache_read_input_tokens: int

    @classmethod
    def from_dict(cls, data: dict) -> "CurrentUsage":
        return cls(
            input_tokens=data["input_tokens"],
            output_tokens=data["output_tokens"],
            cache_creation_input_tokens=data["cache_creation_input_tokens"],
            cache_read_input_tokens=data["cache_read_input_tokens"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["input_tokens"] = self.input_tokens
        result["output_tokens"] = self.output_tokens
        result["cache_creation_input_tokens"] = self.cache_creation_input_tokens
        result["cache_read_input_tokens"] = self.cache_read_input_tokens
        return result


@dataclass(slots=True)
class ContextWindow:
    total_input_tokens: int
    total_output_tokens: int
    context_window_size: int
    used_percentage: float | None = None
    """Null early in session."""
    remaining_percentage: float | None = None
    current_usage: CurrentUsage | None = None
    """Null before the first API call and after /compact."""

    @classmethod
    def from_dict(cls, data: dict) -> "ContextWindow":
        return cls(
            total_input_tokens=data["total_input_tokens"],
            total_output_tokens=data["total_output_tokens"],
            context_window_size=data["context_window_size"],
            used_percentage=data.get("used_percentage"),
            remaining_percentage=data.get("remaining_percentage"),
            current_usage=CurrentUsage.from_dict(data["current_usage"])
            if data.get("current_usage") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["total_input_tokens"] = self.total_input_tokens
        result["total_output_tokens"] = self.total_output_tokens
        result["context_window_size"] = self.context_window_size
        if self.used_percentage is not None:
            result["used_percentage"] = self.used_percentage
        if self.remaining_percentage is not None:
            result["remaining_percentage"] = self.remaining_percentage
        if self.current_usage is not None:
            result["current_usage"] = self.current_usage.to_dict()
        return result


@dataclass(slots=True)
class CostInfo:
    total_cost_usd: float
    total_duration_ms: int
    total_api_duration_ms: int
    total_lines_added: int
    total_lines_removed: int

    @classmethod
    def from_dict(cls, data: dict) -> "CostInfo":
        return cls(
            total_cost_usd=data["total_cost_usd"],
            total_duration_ms=data["total_duration_ms"],
            total_api_duration_ms=data["total_api_duration_ms"],
            total_lines_added=data["total_lines_added"],
            total_lines_removed=data["total_lines_removed"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["total_cost_usd"] = self.total_cost_usd
        result["total_duration_ms"] = self.total_duration_ms
        result["total_api_duration_ms"] = self.total_api_duration_ms
        result["total_lines_added"] = self.total_lines_added
        result["total_lines_removed"] = self.total_lines_removed
        return result


class EffortLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


@dataclass(slots=True)
class EffortObject:
    level: EffortLevel

    @classmethod
    def from_dict(cls, data: dict) -> "EffortObject":
        return cls(
            level=EffortLevel(data["level"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["level"] = self.level.value
        return result


@dataclass(slots=True)
class ModelInfo:
    id: str
    """Model identifier."""
    display_name: str
    """Human-readable model name."""

    @classmethod
    def from_dict(cls, data: dict) -> "ModelInfo":
        return cls(
            id=data["id"],
            display_name=data["display_name"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = self.id
        result["display_name"] = self.display_name
        return result


@dataclass(slots=True)
class OutputStyle:
    name: str

    @classmethod
    def from_dict(cls, data: dict) -> "OutputStyle":
        return cls(
            name=data["name"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = self.name
        return result


class PRReviewState(str, Enum):
    APPROVED = "approved"
    PENDING = "pending"
    CHANGES_REQUESTED = "changes_requested"
    DRAFT = "draft"


@dataclass(slots=True)
class PRInfo:
    number: int
    url: str
    review_state: PRReviewState | None = None
    """May be absent even when pr is present."""

    @classmethod
    def from_dict(cls, data: dict) -> "PRInfo":
        return cls(
            number=data["number"],
            url=data["url"],
            review_state=PRReviewState(data["review_state"]) if data.get("review_state") is not None else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["number"] = self.number
        result["url"] = self.url
        if self.review_state is not None:
            result["review_state"] = self.review_state.value
        return result


@dataclass(slots=True)
class RateLimitWindow:
    used_percentage: float
    resets_at: int
    """Unix epoch seconds."""

    @classmethod
    def from_dict(cls, data: dict) -> "RateLimitWindow":
        return cls(
            used_percentage=data["used_percentage"],
            resets_at=data["resets_at"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["used_percentage"] = self.used_percentage
        result["resets_at"] = self.resets_at
        return result


@dataclass(slots=True)
class RateLimits:
    five_hour: RateLimitWindow | None = None
    seven_day: RateLimitWindow | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "RateLimits":
        return cls(
            five_hour=RateLimitWindow.from_dict(data["five_hour"]) if data.get("five_hour") is not None else None,
            seven_day=RateLimitWindow.from_dict(data["seven_day"]) if data.get("seven_day") is not None else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        if self.five_hour is not None:
            result["five_hour"] = self.five_hour.to_dict()
        if self.seven_day is not None:
            result["seven_day"] = self.seven_day.to_dict()
        return result


@dataclass(slots=True)
class ThinkingInfo:
    enabled: bool

    @classmethod
    def from_dict(cls, data: dict) -> "ThinkingInfo":
        return cls(
            enabled=data["enabled"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["enabled"] = self.enabled
        return result


class VimMode(str, Enum):
    NORMAL = "NORMAL"
    INSERT = "INSERT"
    VISUAL = "VISUAL"
    VISUAL_LINE = "VISUAL LINE"


@dataclass(slots=True)
class VimInfo:
    mode: VimMode

    @classmethod
    def from_dict(cls, data: dict) -> "VimInfo":
        return cls(
            mode=VimMode(data["mode"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["mode"] = self.mode.value
        return result


@dataclass(slots=True)
class RepoInfo:
    host: str
    """Git host, e.g. github.com."""
    owner: str
    name: str

    @classmethod
    def from_dict(cls, data: dict) -> "RepoInfo":
        return cls(
            host=data["host"],
            owner=data["owner"],
            name=data["name"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["host"] = self.host
        result["owner"] = self.owner
        result["name"] = self.name
        return result


@dataclass(slots=True)
class WorkspaceInfo:
    current_dir: str
    project_dir: str
    added_dirs: list[str]
    git_worktree: str | None = None
    """Absent outside a linked git worktree."""
    repo: RepoInfo | None = None
    """Absent outside git repos with an origin remote."""

    @classmethod
    def from_dict(cls, data: dict) -> "WorkspaceInfo":
        return cls(
            current_dir=data["current_dir"],
            project_dir=data["project_dir"],
            added_dirs=data["added_dirs"],
            git_worktree=data.get("git_worktree"),
            repo=RepoInfo.from_dict(data["repo"]) if data.get("repo") is not None else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["current_dir"] = self.current_dir
        result["project_dir"] = self.project_dir
        result["added_dirs"] = self.added_dirs
        if self.git_worktree is not None:
            result["git_worktree"] = self.git_worktree
        if self.repo is not None:
            result["repo"] = self.repo.to_dict()
        return result


@dataclass(slots=True)
class WorktreeInfo:
    name: str
    path: str
    original_cwd: str
    branch: str | None = None
    """Absent for hook-based worktrees."""
    original_branch: str | None = None
    """Absent for hook-based worktrees."""

    @classmethod
    def from_dict(cls, data: dict) -> "WorktreeInfo":
        return cls(
            name=data["name"],
            path=data["path"],
            original_cwd=data["original_cwd"],
            branch=data.get("branch"),
            original_branch=data.get("original_branch"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = self.name
        result["path"] = self.path
        result["original_cwd"] = self.original_cwd
        if self.branch is not None:
            result["branch"] = self.branch
        if self.original_branch is not None:
            result["original_branch"] = self.original_branch
        return result


@dataclass(slots=True)
class StatusLineData:
    """The whole statusLine contract — statusLine has no output schema (D3); inputs are authored entirely from capture."""

    cwd: str
    session_id: str
    transcript_path: str
    version: str
    exceeds_200k_tokens: bool
    fast_mode: bool
    """Whether fast mode is active."""
    model: ModelInfo
    workspace: WorkspaceInfo
    output_style: OutputStyle
    cost: CostInfo
    context_window: ContextWindow
    thinking: ThinkingInfo
    session_name: str | None = None
    """The session name — set via --name or /rename, or auto-generated by Claude Code from the conversation."""
    prompt_id: str | None = None
    """UUID identifying the user prompt currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so status line output can be correlated with telemetry for a single prompt. Absent until first user input (v2.1.196+)."""
    effort: EffortObject | None = None
    rate_limits: RateLimits | None = None
    """Pro/Max subscribers only, after the first API response."""
    vim: VimInfo | None = None
    agent: AgentInfo | None = None
    pr: PRInfo | None = None
    worktree: WorktreeInfo | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "StatusLineData":
        return cls(
            cwd=data["cwd"],
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            version=data["version"],
            exceeds_200k_tokens=data["exceeds_200k_tokens"],
            fast_mode=data["fast_mode"],
            model=ModelInfo.from_dict(data["model"]),
            workspace=WorkspaceInfo.from_dict(data["workspace"]),
            output_style=OutputStyle.from_dict(data["output_style"]),
            cost=CostInfo.from_dict(data["cost"]),
            context_window=ContextWindow.from_dict(data["context_window"]),
            thinking=ThinkingInfo.from_dict(data["thinking"]),
            session_name=data.get("session_name"),
            prompt_id=data.get("prompt_id"),
            effort=EffortObject.from_dict(data["effort"]) if data.get("effort") is not None else None,
            rate_limits=RateLimits.from_dict(data["rate_limits"]) if data.get("rate_limits") is not None else None,
            vim=VimInfo.from_dict(data["vim"]) if data.get("vim") is not None else None,
            agent=AgentInfo.from_dict(data["agent"]) if data.get("agent") is not None else None,
            pr=PRInfo.from_dict(data["pr"]) if data.get("pr") is not None else None,
            worktree=WorktreeInfo.from_dict(data["worktree"]) if data.get("worktree") is not None else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["cwd"] = self.cwd
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["version"] = self.version
        result["exceeds_200k_tokens"] = self.exceeds_200k_tokens
        result["fast_mode"] = self.fast_mode
        result["model"] = self.model.to_dict()
        result["workspace"] = self.workspace.to_dict()
        result["output_style"] = self.output_style.to_dict()
        result["cost"] = self.cost.to_dict()
        result["context_window"] = self.context_window.to_dict()
        result["thinking"] = self.thinking.to_dict()
        if self.session_name is not None:
            result["session_name"] = self.session_name
        if self.prompt_id is not None:
            result["prompt_id"] = self.prompt_id
        if self.effort is not None:
            result["effort"] = self.effort.to_dict()
        if self.rate_limits is not None:
            result["rate_limits"] = self.rate_limits.to_dict()
        if self.vim is not None:
            result["vim"] = self.vim.to_dict()
        if self.agent is not None:
            result["agent"] = self.agent.to_dict()
        if self.pr is not None:
            result["pr"] = self.pr.to_dict()
        if self.worktree is not None:
            result["worktree"] = self.worktree.to_dict()
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = StatusLineData.from_dict(json.loads(sys.stdin.read()))
    # Freeform text surface (statusLine). No output model — print exactly what handle() returns.
    line = handle(event)
    print(line)
    return 0
