// Generated by cc-flyrig from the Claude Code statusline IR — do not edit.
// Source schema: cc-2.1.206 (2026-07-10). Re-scaffold when Claude Code is upgraded.
// Event: StatusLine. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export interface AgentInfo {
  name: string;
}

export interface CurrentUsage {
  inputTokens: number;
  outputTokens: number;
  cacheCreationInputTokens: number;
  cacheReadInputTokens: number;
}

export interface ContextWindow {
  totalInputTokens: number;
  totalOutputTokens: number;
  contextWindowSize: number;
  /** Null early in session. */
  usedPercentage?: number;
  remainingPercentage?: number;
  /** Null before the first API call and after /compact. */
  currentUsage?: CurrentUsage;
}

export interface CostInfo {
  totalCostUsd: number;
  totalDurationMs: number;
  totalApiDurationMs: number;
  totalLinesAdded: number;
  totalLinesRemoved: number;
}

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export interface ModelInfo {
  /** Model identifier. */
  id: string;
  /** Human-readable model name. */
  displayName: string;
}

export interface OutputStyle {
  name: string;
}

export type PRReviewState = "approved" | "pending" | "changes_requested" | "draft";

export interface PRInfo {
  number: number;
  url: string;
  /** May be absent even when pr is present. */
  reviewState?: PRReviewState;
}

export interface RateLimitWindow {
  usedPercentage: number;
  /** Unix epoch seconds. */
  resetsAt: number;
}

export interface RateLimits {
  fiveHour?: RateLimitWindow;
  sevenDay?: RateLimitWindow;
}

export interface ThinkingInfo {
  enabled: boolean;
}

export type VimMode = "NORMAL" | "INSERT" | "VISUAL" | "VISUAL LINE";

export interface VimInfo {
  mode: VimMode;
}

export interface RepoInfo {
  /** Git host, e.g. github.com. */
  host: string;
  owner: string;
  name: string;
}

export interface WorkspaceInfo {
  currentDir: string;
  projectDir: string;
  addedDirs: string[];
  /** Absent outside a linked git worktree. */
  gitWorktree?: string;
  /** Absent outside git repos with an origin remote. */
  repo?: RepoInfo;
}

export interface WorktreeInfo {
  name: string;
  path: string;
  originalCwd: string;
  /** Absent for hook-based worktrees. */
  branch?: string;
  /** Absent for hook-based worktrees. */
  originalBranch?: string;
}

/** The whole statusLine contract — statusLine has no output schema (D3); inputs are authored entirely from capture. */
export interface StatusLineData {
  cwd: string;
  sessionId: string;
  transcriptPath: string;
  version: string;
  exceeds200kTokens: boolean;
  /** Whether fast mode is active. */
  fastMode: boolean;
  model: ModelInfo;
  workspace: WorkspaceInfo;
  outputStyle: OutputStyle;
  cost: CostInfo;
  contextWindow: ContextWindow;
  thinking: ThinkingInfo;
  /** The session name — set via --name or /rename, or auto-generated by Claude Code from the conversation. */
  sessionName?: string;
  /** UUID identifying the user prompt currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so status line output can be correlated with telemetry for a single prompt. Absent until first user input (v2.1.196+). */
  promptId?: string;
  effort?: EffortObject;
  /** Pro/Max subscribers only, after the first API response. */
  rateLimits?: RateLimits;
  vim?: VimInfo;
  agent?: AgentInfo;
  pr?: PRInfo;
  worktree?: WorktreeInfo;
}

export function parseAgentInfo(data: Record<string, any>): AgentInfo {
  return {
    name: data["name"],
  };
}

export function parseCurrentUsage(data: Record<string, any>): CurrentUsage {
  return {
    inputTokens: data["input_tokens"],
    outputTokens: data["output_tokens"],
    cacheCreationInputTokens: data["cache_creation_input_tokens"],
    cacheReadInputTokens: data["cache_read_input_tokens"],
  };
}

export function parseContextWindow(data: Record<string, any>): ContextWindow {
  return {
    totalInputTokens: data["total_input_tokens"],
    totalOutputTokens: data["total_output_tokens"],
    contextWindowSize: data["context_window_size"],
    usedPercentage: data["used_percentage"] ?? undefined,
    remainingPercentage: data["remaining_percentage"] ?? undefined,
    currentUsage: data["current_usage"] != null ? parseCurrentUsage(data["current_usage"]) : undefined,
  };
}

export function parseCostInfo(data: Record<string, any>): CostInfo {
  return {
    totalCostUsd: data["total_cost_usd"],
    totalDurationMs: data["total_duration_ms"],
    totalApiDurationMs: data["total_api_duration_ms"],
    totalLinesAdded: data["total_lines_added"],
    totalLinesRemoved: data["total_lines_removed"],
  };
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseModelInfo(data: Record<string, any>): ModelInfo {
  return {
    id: data["id"],
    displayName: data["display_name"],
  };
}

export function parseOutputStyle(data: Record<string, any>): OutputStyle {
  return {
    name: data["name"],
  };
}

export function parsePRInfo(data: Record<string, any>): PRInfo {
  return {
    number: data["number"],
    url: data["url"],
    reviewState: data["review_state"] ?? undefined,
  };
}

export function parseRateLimitWindow(data: Record<string, any>): RateLimitWindow {
  return {
    usedPercentage: data["used_percentage"],
    resetsAt: data["resets_at"],
  };
}

export function parseRateLimits(data: Record<string, any>): RateLimits {
  return {
    fiveHour: data["five_hour"] != null ? parseRateLimitWindow(data["five_hour"]) : undefined,
    sevenDay: data["seven_day"] != null ? parseRateLimitWindow(data["seven_day"]) : undefined,
  };
}

export function parseThinkingInfo(data: Record<string, any>): ThinkingInfo {
  return {
    enabled: data["enabled"],
  };
}

export function parseVimInfo(data: Record<string, any>): VimInfo {
  return {
    mode: data["mode"],
  };
}

export function parseRepoInfo(data: Record<string, any>): RepoInfo {
  return {
    host: data["host"],
    owner: data["owner"],
    name: data["name"],
  };
}

export function parseWorkspaceInfo(data: Record<string, any>): WorkspaceInfo {
  return {
    currentDir: data["current_dir"],
    projectDir: data["project_dir"],
    addedDirs: data["added_dirs"],
    gitWorktree: data["git_worktree"] ?? undefined,
    repo: data["repo"] != null ? parseRepoInfo(data["repo"]) : undefined,
  };
}

export function parseWorktreeInfo(data: Record<string, any>): WorktreeInfo {
  return {
    name: data["name"],
    path: data["path"],
    originalCwd: data["original_cwd"],
    branch: data["branch"] ?? undefined,
    originalBranch: data["original_branch"] ?? undefined,
  };
}

export function parseStatusLineData(data: Record<string, any>): StatusLineData {
  return {
    cwd: data["cwd"],
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    version: data["version"],
    exceeds200kTokens: data["exceeds_200k_tokens"],
    fastMode: data["fast_mode"],
    model: parseModelInfo(data["model"]),
    workspace: parseWorkspaceInfo(data["workspace"]),
    outputStyle: parseOutputStyle(data["output_style"]),
    cost: parseCostInfo(data["cost"]),
    contextWindow: parseContextWindow(data["context_window"]),
    thinking: parseThinkingInfo(data["thinking"]),
    sessionName: data["session_name"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    rateLimits: data["rate_limits"] != null ? parseRateLimits(data["rate_limits"]) : undefined,
    vim: data["vim"] != null ? parseVimInfo(data["vim"]) : undefined,
    agent: data["agent"] != null ? parseAgentInfo(data["agent"]) : undefined,
    pr: data["pr"] != null ? parsePRInfo(data["pr"]) : undefined,
    worktree: data["worktree"] != null ? parseWorktreeInfo(data["worktree"]) : undefined,
  };
}

export function serializeAgentInfo(obj: AgentInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["name"] = obj.name;
  return result;
}

export function serializeCurrentUsage(obj: CurrentUsage): Record<string, any> {
  const result: Record<string, any> = {};
  result["input_tokens"] = obj.inputTokens;
  result["output_tokens"] = obj.outputTokens;
  result["cache_creation_input_tokens"] = obj.cacheCreationInputTokens;
  result["cache_read_input_tokens"] = obj.cacheReadInputTokens;
  return result;
}

export function serializeContextWindow(obj: ContextWindow): Record<string, any> {
  const result: Record<string, any> = {};
  result["total_input_tokens"] = obj.totalInputTokens;
  result["total_output_tokens"] = obj.totalOutputTokens;
  result["context_window_size"] = obj.contextWindowSize;
  if (obj.usedPercentage !== undefined) {
    result["used_percentage"] = obj.usedPercentage;
  }
  if (obj.remainingPercentage !== undefined) {
    result["remaining_percentage"] = obj.remainingPercentage;
  }
  if (obj.currentUsage !== undefined) {
    result["current_usage"] = serializeCurrentUsage(obj.currentUsage);
  }
  return result;
}

export function serializeCostInfo(obj: CostInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["total_cost_usd"] = obj.totalCostUsd;
  result["total_duration_ms"] = obj.totalDurationMs;
  result["total_api_duration_ms"] = obj.totalApiDurationMs;
  result["total_lines_added"] = obj.totalLinesAdded;
  result["total_lines_removed"] = obj.totalLinesRemoved;
  return result;
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeModelInfo(obj: ModelInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["id"] = obj.id;
  result["display_name"] = obj.displayName;
  return result;
}

export function serializeOutputStyle(obj: OutputStyle): Record<string, any> {
  const result: Record<string, any> = {};
  result["name"] = obj.name;
  return result;
}

export function serializePRInfo(obj: PRInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["number"] = obj.number;
  result["url"] = obj.url;
  if (obj.reviewState !== undefined) {
    result["review_state"] = obj.reviewState;
  }
  return result;
}

export function serializeRateLimitWindow(obj: RateLimitWindow): Record<string, any> {
  const result: Record<string, any> = {};
  result["used_percentage"] = obj.usedPercentage;
  result["resets_at"] = obj.resetsAt;
  return result;
}

export function serializeRateLimits(obj: RateLimits): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.fiveHour !== undefined) {
    result["five_hour"] = serializeRateLimitWindow(obj.fiveHour);
  }
  if (obj.sevenDay !== undefined) {
    result["seven_day"] = serializeRateLimitWindow(obj.sevenDay);
  }
  return result;
}

export function serializeThinkingInfo(obj: ThinkingInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["enabled"] = obj.enabled;
  return result;
}

export function serializeVimInfo(obj: VimInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["mode"] = obj.mode;
  return result;
}

export function serializeRepoInfo(obj: RepoInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["host"] = obj.host;
  result["owner"] = obj.owner;
  result["name"] = obj.name;
  return result;
}

export function serializeWorkspaceInfo(obj: WorkspaceInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["current_dir"] = obj.currentDir;
  result["project_dir"] = obj.projectDir;
  result["added_dirs"] = obj.addedDirs;
  if (obj.gitWorktree !== undefined) {
    result["git_worktree"] = obj.gitWorktree;
  }
  if (obj.repo !== undefined) {
    result["repo"] = serializeRepoInfo(obj.repo);
  }
  return result;
}

export function serializeWorktreeInfo(obj: WorktreeInfo): Record<string, any> {
  const result: Record<string, any> = {};
  result["name"] = obj.name;
  result["path"] = obj.path;
  result["original_cwd"] = obj.originalCwd;
  if (obj.branch !== undefined) {
    result["branch"] = obj.branch;
  }
  if (obj.originalBranch !== undefined) {
    result["original_branch"] = obj.originalBranch;
  }
  return result;
}

export function serializeStatusLineData(obj: StatusLineData): Record<string, any> {
  const result: Record<string, any> = {};
  result["cwd"] = obj.cwd;
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["version"] = obj.version;
  result["exceeds_200k_tokens"] = obj.exceeds200kTokens;
  result["fast_mode"] = obj.fastMode;
  result["model"] = serializeModelInfo(obj.model);
  result["workspace"] = serializeWorkspaceInfo(obj.workspace);
  result["output_style"] = serializeOutputStyle(obj.outputStyle);
  result["cost"] = serializeCostInfo(obj.cost);
  result["context_window"] = serializeContextWindow(obj.contextWindow);
  result["thinking"] = serializeThinkingInfo(obj.thinking);
  if (obj.sessionName !== undefined) {
    result["session_name"] = obj.sessionName;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.rateLimits !== undefined) {
    result["rate_limits"] = serializeRateLimits(obj.rateLimits);
  }
  if (obj.vim !== undefined) {
    result["vim"] = serializeVimInfo(obj.vim);
  }
  if (obj.agent !== undefined) {
    result["agent"] = serializeAgentInfo(obj.agent);
  }
  if (obj.pr !== undefined) {
    result["pr"] = serializePRInfo(obj.pr);
  }
  if (obj.worktree !== undefined) {
    result["worktree"] = serializeWorktreeInfo(obj.worktree);
  }
  return result;
}

export function run(handle: (event: StatusLineData) => string): void {
  const event = parseStatusLineData(JSON.parse(readStdin()));
  // Freeform text surface (statusLine). No output model — print exactly what handle() returns.
  console.log(handle(event));
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
