# Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
# Source schema: cc-2.1.183 (2026-06-20). Re-scaffold when Claude Code is upgraded.
# Event: SubagentStop. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Literal


@dataclass(slots=True)
class BackgroundTask:
    id: str
    """Task identifier."""
    type: str
    """Friendly task-type label such as shell, subagent, monitor, workflow, teammate, cloud session, or MCP task."""
    status: str
    """Current task status."""
    description: str
    """Free-text description, capped at 1000 characters."""
    command: str | None = None
    """Shell command line. Present only for shell tasks."""
    agent_type: str | None = None
    """Subagent type name. Present only for subagent tasks."""
    server: str | None = None
    """MCP server name. Present only for monitor and MCP task tasks."""
    tool: str | None = None
    """MCP tool name. Present only for monitor and MCP task tasks."""
    name: str | None = None
    """Workflow name. Present only for workflow tasks."""

    @classmethod
    def from_dict(cls, data: dict) -> "BackgroundTask":
        return cls(
            id=data["id"],
            type=data["type"],
            status=data["status"],
            description=data["description"],
            command=data.get("command"),
            agent_type=data.get("agent_type"),
            server=data.get("server"),
            tool=data.get("tool"),
            name=data.get("name"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = self.id
        result["type"] = self.type
        result["status"] = self.status
        result["description"] = self.description
        if self.command is not None:
            result["command"] = self.command
        if self.agent_type is not None:
            result["agent_type"] = self.agent_type
        if self.server is not None:
            result["server"] = self.server
        if self.tool is not None:
            result["tool"] = self.tool
        if self.name is not None:
            result["name"] = self.name
        return result


class EffortLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


@dataclass(slots=True)
class EffortObject:
    level: EffortLevel

    @classmethod
    def from_dict(cls, data: dict) -> "EffortObject":
        return cls(
            level=EffortLevel(data["level"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["level"] = self.level.value
        return result


class PermissionMode(str, Enum):
    DEFAULT = "default"
    PLAN = "plan"
    ACCEPT_EDITS = "acceptEdits"
    AUTO = "auto"
    DONT_ASK = "dontAsk"
    BYPASS_PERMISSIONS = "bypassPermissions"


@dataclass(slots=True)
class SessionCron:
    id: str
    """Cron task identifier."""
    schedule: str
    """Cron expression, for example 0 9 * * 1-5."""
    recurring: bool
    """false for one-shot wakeups, true for tasks that re-fire on every match."""
    prompt: str
    """Prompt submitted when the cron fires, capped at 1000 characters."""

    @classmethod
    def from_dict(cls, data: dict) -> "SessionCron":
        return cls(
            id=data["id"],
            schedule=data["schedule"],
            recurring=data["recurring"],
            prompt=data["prompt"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = self.id
        result["schedule"] = self.schedule
        result["recurring"] = self.recurring
        result["prompt"] = self.prompt
        return result


@dataclass(slots=True)
class SubagentStopInput:
    session_id: str
    """Current session identifier."""
    transcript_path: str
    """Path to conversation JSON."""
    cwd: str
    """Current working directory when the hook is invoked."""
    hook_event_name: str
    """Name of the event that fired."""
    agent_id: str
    """Unique identifier for the subagent."""
    agent_type: str
    """Agent name used for matcher filtering."""
    stop_hook_active: bool
    """true when Claude Code is already continuing as a result of a stop hook."""
    agent_transcript_path: str
    """Path to the subagent's own transcript stored in a nested subagents/ folder."""
    permission_mode: PermissionMode | None = None
    """Current permission mode. Not all events include this field."""
    effort: EffortObject | None = None
    """Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter."""
    last_assistant_message: str | None = None
    """Text content of the subagent's final response."""
    background_tasks: list[BackgroundTask] | None = None
    """In-flight background tasks scoped to the parent session."""
    session_crons: list[SessionCron] | None = None
    """Session-scoped scheduled wakeups scoped to the parent session."""

    @classmethod
    def from_dict(cls, data: dict) -> "SubagentStopInput":
        return cls(
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            cwd=data["cwd"],
            hook_event_name=data["hook_event_name"],
            agent_id=data["agent_id"],
            agent_type=data["agent_type"],
            stop_hook_active=data["stop_hook_active"],
            agent_transcript_path=data["agent_transcript_path"],
            permission_mode=PermissionMode(data["permission_mode"])
            if data.get("permission_mode") is not None
            else None,
            effort=EffortObject.from_dict(data["effort"]) if data.get("effort") is not None else None,
            last_assistant_message=data.get("last_assistant_message"),
            background_tasks=[BackgroundTask.from_dict(_v) for _v in data["background_tasks"]]
            if data.get("background_tasks") is not None
            else None,
            session_crons=[SessionCron.from_dict(_v) for _v in data["session_crons"]]
            if data.get("session_crons") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["cwd"] = self.cwd
        result["hook_event_name"] = self.hook_event_name
        result["agent_id"] = self.agent_id
        result["agent_type"] = self.agent_type
        result["stop_hook_active"] = self.stop_hook_active
        result["agent_transcript_path"] = self.agent_transcript_path
        if self.permission_mode is not None:
            result["permission_mode"] = self.permission_mode.value
        if self.effort is not None:
            result["effort"] = self.effort.to_dict()
        if self.last_assistant_message is not None:
            result["last_assistant_message"] = self.last_assistant_message
        if self.background_tasks is not None:
            result["background_tasks"] = [_v.to_dict() for _v in self.background_tasks]
        if self.session_crons is not None:
            result["session_crons"] = [_v.to_dict() for _v in self.session_crons]
        return result


@dataclass(slots=True)
class SubagentStopHookSpecificOutput:
    hook_event_name: Literal["SubagentStop"]
    additional_context: str | None = None
    """Non-error feedback for the subagent. Conversation continues without a hook error notification."""

    @classmethod
    def from_dict(cls, data: dict) -> "SubagentStopHookSpecificOutput":
        return cls(
            hook_event_name=data["hookEventName"],
            additional_context=data.get("additionalContext"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["hookEventName"] = self.hook_event_name
        if self.additional_context is not None:
            result["additionalContext"] = self.additional_context
        return result


@dataclass(slots=True)
class SubagentStopOutput:
    continue_: bool | None = None
    """If false, Claude stops processing entirely after the hook runs."""
    stop_reason: str | None = None
    """Message shown to the user when continue is false. Not shown to Claude."""
    suppress_output: bool | None = None
    """If true, hides the hook's stdout from the transcript."""
    system_message: str | None = None
    """Warning message shown to the user."""
    terminal_sequence: str | None = None
    """One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored."""
    decision: Literal["block"] | None = None
    """block keeps the subagent running and delivers reason to the subagent as its next instruction."""
    reason: str | None = None
    """Required when decision is block."""
    hook_specific_output: SubagentStopHookSpecificOutput | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "SubagentStopOutput":
        return cls(
            continue_=data.get("continue"),
            stop_reason=data.get("stopReason"),
            suppress_output=data.get("suppressOutput"),
            system_message=data.get("systemMessage"),
            terminal_sequence=data.get("terminalSequence"),
            decision=data.get("decision"),
            reason=data.get("reason"),
            hook_specific_output=SubagentStopHookSpecificOutput.from_dict(data["hookSpecificOutput"])
            if data.get("hookSpecificOutput") is not None
            else None,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        if self.continue_ is not None:
            result["continue"] = self.continue_
        if self.stop_reason is not None:
            result["stopReason"] = self.stop_reason
        if self.suppress_output is not None:
            result["suppressOutput"] = self.suppress_output
        if self.system_message is not None:
            result["systemMessage"] = self.system_message
        if self.terminal_sequence is not None:
            result["terminalSequence"] = self.terminal_sequence
        if self.decision is not None:
            result["decision"] = self.decision
        if self.reason is not None:
            result["reason"] = self.reason
        if self.hook_specific_output is not None:
            result["hookSpecificOutput"] = self.hook_specific_output.to_dict()
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = SubagentStopInput.from_dict(json.loads(sys.stdin.read()))
    # Blocking event. Set decision="block" and reason to stop the action. Returning None allows.
    decision = handle(event)
    if decision is not None:
        print(json.dumps(decision.to_dict()))
    return 0
