// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.200 (2026-07-03). Re-scaffold when Claude Code is upgraded.
// Event: SubagentStop. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export interface BackgroundTask {
  /** Task identifier. */
  id: string;
  /** Friendly task-type label such as shell, subagent, monitor, workflow, teammate, cloud session, or MCP task. */
  type: string;
  /** Current task status. */
  status: string;
  /** Free-text description, capped at 1000 characters. */
  description: string;
  /** Shell command line. Present only for shell tasks. */
  command?: string;
  /** Subagent type name. Present only for subagent tasks. */
  agentType?: string;
  /** MCP server name. Present only for monitor and MCP task tasks. */
  server?: string;
  /** MCP tool name. Present only for monitor and MCP task tasks. */
  tool?: string;
  /** Workflow name. Present only for workflow tasks. */
  name?: string;
}

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface SessionCron {
  /** Cron task identifier. */
  id: string;
  /** Cron expression, for example 0 9 * * 1-5. */
  schedule: string;
  /** false for one-shot wakeups, true for tasks that re-fire on every match. */
  recurring: boolean;
  /** Prompt submitted when the cron fires, capped at 1000 characters. */
  prompt: string;
}

export interface SubagentStopInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Unique identifier for the subagent. */
  agentId: string;
  /** Agent name used for matcher filtering. */
  agentType: string;
  /** true when Claude Code is already continuing as a result of a stop hook. */
  stopHookActive: boolean;
  /** Path to the subagent's own transcript stored in a nested subagents/ folder. */
  agentTranscriptPath: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
  /** Text content of the subagent's final response. */
  lastAssistantMessage?: string;
  /** In-flight background tasks scoped to the parent session. */
  backgroundTasks?: BackgroundTask[];
  /** Session-scoped scheduled wakeups scoped to the parent session. */
  sessionCrons?: SessionCron[];
}

export interface SubagentStopHookSpecificOutput {
  hookEventName: "SubagentStop";
  /** Non-error feedback for the subagent. Conversation continues without a hook error notification. */
  additionalContext?: string;
}

export interface SubagentStopOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  /** block keeps the subagent running and delivers reason to the subagent as its next instruction. */
  decision?: "block";
  /** Required when decision is block. */
  reason?: string;
  hookSpecificOutput?: SubagentStopHookSpecificOutput;
}

export function parseBackgroundTask(data: Record<string, any>): BackgroundTask {
  return {
    id: data["id"],
    type: data["type"],
    status: data["status"],
    description: data["description"],
    command: data["command"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    server: data["server"] ?? undefined,
    tool: data["tool"] ?? undefined,
    name: data["name"] ?? undefined,
  };
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseSessionCron(data: Record<string, any>): SessionCron {
  return {
    id: data["id"],
    schedule: data["schedule"],
    recurring: data["recurring"],
    prompt: data["prompt"],
  };
}

export function parseSubagentStopInput(data: Record<string, any>): SubagentStopInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    agentId: data["agent_id"],
    agentType: data["agent_type"],
    stopHookActive: data["stop_hook_active"],
    agentTranscriptPath: data["agent_transcript_path"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    promptId: data["prompt_id"] ?? undefined,
    lastAssistantMessage: data["last_assistant_message"] ?? undefined,
    backgroundTasks: data["background_tasks"] != null ? data["background_tasks"].map(parseBackgroundTask) : undefined,
    sessionCrons: data["session_crons"] != null ? data["session_crons"].map(parseSessionCron) : undefined,
  };
}

export function parseSubagentStopHookSpecificOutput(data: Record<string, any>): SubagentStopHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    additionalContext: data["additionalContext"] ?? undefined,
  };
}

export function parseSubagentStopOutput(data: Record<string, any>): SubagentStopOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    decision: data["decision"] ?? undefined,
    reason: data["reason"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parseSubagentStopHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeBackgroundTask(obj: BackgroundTask): Record<string, any> {
  const result: Record<string, any> = {};
  result["id"] = obj.id;
  result["type"] = obj.type;
  result["status"] = obj.status;
  result["description"] = obj.description;
  if (obj.command !== undefined) {
    result["command"] = obj.command;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.server !== undefined) {
    result["server"] = obj.server;
  }
  if (obj.tool !== undefined) {
    result["tool"] = obj.tool;
  }
  if (obj.name !== undefined) {
    result["name"] = obj.name;
  }
  return result;
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeSessionCron(obj: SessionCron): Record<string, any> {
  const result: Record<string, any> = {};
  result["id"] = obj.id;
  result["schedule"] = obj.schedule;
  result["recurring"] = obj.recurring;
  result["prompt"] = obj.prompt;
  return result;
}

export function serializeSubagentStopInput(obj: SubagentStopInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["agent_id"] = obj.agentId;
  result["agent_type"] = obj.agentType;
  result["stop_hook_active"] = obj.stopHookActive;
  result["agent_transcript_path"] = obj.agentTranscriptPath;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.lastAssistantMessage !== undefined) {
    result["last_assistant_message"] = obj.lastAssistantMessage;
  }
  if (obj.backgroundTasks !== undefined) {
    result["background_tasks"] = obj.backgroundTasks.map(serializeBackgroundTask);
  }
  if (obj.sessionCrons !== undefined) {
    result["session_crons"] = obj.sessionCrons.map(serializeSessionCron);
  }
  return result;
}

export function serializeSubagentStopHookSpecificOutput(obj: SubagentStopHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  return result;
}

export function serializeSubagentStopOutput(obj: SubagentStopOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.decision !== undefined) {
    result["decision"] = obj.decision;
  }
  if (obj.reason !== undefined) {
    result["reason"] = obj.reason;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializeSubagentStopHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: SubagentStopInput) => SubagentStopOutput | null): void {
  const event = parseSubagentStopInput(JSON.parse(readStdin()));
  // Blocking event. Set decision="block" and reason to stop the action. Returning null allows.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeSubagentStopOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
