# Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
# Source schema: cc-2.1.185 (2026-06-20). Re-scaffold when Claude Code is upgraded.
# Event: PreCompact. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Literal


class EffortLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


@dataclass(slots=True)
class EffortObject:
    level: EffortLevel

    @classmethod
    def from_dict(cls, data: dict) -> "EffortObject":
        return cls(
            level=EffortLevel(data["level"]),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["level"] = self.level.value
        return result


class PermissionMode(str, Enum):
    DEFAULT = "default"
    PLAN = "plan"
    ACCEPT_EDITS = "acceptEdits"
    AUTO = "auto"
    DONT_ASK = "dontAsk"
    BYPASS_PERMISSIONS = "bypassPermissions"


@dataclass(slots=True)
class PreCompactInput:
    session_id: str
    """Current session identifier."""
    transcript_path: str
    """Path to conversation JSON."""
    cwd: str
    """Current working directory when the hook is invoked."""
    hook_event_name: str
    """Name of the event that fired."""
    trigger: Literal["manual", "auto"]
    """Whether compaction was triggered manually (/compact) or automatically."""
    permission_mode: PermissionMode | None = None
    """Current permission mode. Not all events include this field."""
    effort: EffortObject | None = None
    """Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter."""
    agent_id: str | None = None
    """Unique identifier for the subagent. Present only when the hook fires inside a subagent call."""
    agent_type: str | None = None
    """Agent name. Present when the session uses --agent or the hook fires inside a subagent."""
    custom_instructions: str | None = None
    """For manual: what the user passed into /compact, or null when none was passed. For auto: empty string or null."""

    @classmethod
    def from_dict(cls, data: dict) -> "PreCompactInput":
        return cls(
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            cwd=data["cwd"],
            hook_event_name=data["hook_event_name"],
            trigger=data["trigger"],
            permission_mode=PermissionMode(data["permission_mode"])
            if data.get("permission_mode") is not None
            else None,
            effort=EffortObject.from_dict(data["effort"]) if data.get("effort") is not None else None,
            agent_id=data.get("agent_id"),
            agent_type=data.get("agent_type"),
            custom_instructions=data.get("custom_instructions"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["cwd"] = self.cwd
        result["hook_event_name"] = self.hook_event_name
        result["trigger"] = self.trigger
        if self.permission_mode is not None:
            result["permission_mode"] = self.permission_mode.value
        if self.effort is not None:
            result["effort"] = self.effort.to_dict()
        if self.agent_id is not None:
            result["agent_id"] = self.agent_id
        if self.agent_type is not None:
            result["agent_type"] = self.agent_type
        if self.custom_instructions is not None:
            result["custom_instructions"] = self.custom_instructions
        return result


@dataclass(slots=True)
class PreCompactOutput:
    continue_: bool | None = None
    """If false, Claude stops processing entirely after the hook runs."""
    stop_reason: str | None = None
    """Message shown to the user when continue is false. Not shown to Claude."""
    suppress_output: bool | None = None
    """If true, hides the hook's stdout from the transcript."""
    system_message: str | None = None
    """Warning message shown to the user."""
    terminal_sequence: str | None = None
    """One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored."""
    decision: Literal["block"] | None = None
    """block prevents compaction. For manual /compact the stderr message is shown to the user."""
    reason: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "PreCompactOutput":
        return cls(
            continue_=data.get("continue"),
            stop_reason=data.get("stopReason"),
            suppress_output=data.get("suppressOutput"),
            system_message=data.get("systemMessage"),
            terminal_sequence=data.get("terminalSequence"),
            decision=data.get("decision"),
            reason=data.get("reason"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        if self.continue_ is not None:
            result["continue"] = self.continue_
        if self.stop_reason is not None:
            result["stopReason"] = self.stop_reason
        if self.suppress_output is not None:
            result["suppressOutput"] = self.suppress_output
        if self.system_message is not None:
            result["systemMessage"] = self.system_message
        if self.terminal_sequence is not None:
            result["terminalSequence"] = self.terminal_sequence
        if self.decision is not None:
            result["decision"] = self.decision
        if self.reason is not None:
            result["reason"] = self.reason
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = PreCompactInput.from_dict(json.loads(sys.stdin.read()))
    # Blocking event. Set decision="block" and reason to stop the action. Returning None allows.
    decision = handle(event)
    if decision is not None:
        print(json.dumps(decision.to_dict()))
    return 0
