// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.185 (2026-06-20). Re-scaffold when Claude Code is upgraded.
// Event: UserPromptExpansion. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface UserPromptExpansionInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** slash_command for skill and custom commands, mcp_prompt for MCP server prompts. */
  expansionType: "slash_command" | "mcp_prompt";
  /** The command name that was expanded. */
  commandName: string;
  /** The original prompt string. */
  prompt: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** Arguments passed to the command. */
  commandArgs?: string;
  /** Source of the command (e.g. plugin). */
  commandSource?: string;
}

export interface UserPromptExpansionHookSpecificOutput {
  hookEventName: "UserPromptExpansion";
  /** String added to Claude's context alongside the expanded prompt. */
  additionalContext?: string;
}

export interface UserPromptExpansionOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  /** block prevents the slash command from expanding. Omit to allow. */
  decision?: "block";
  /** Shown to the user when decision is block. */
  reason?: string;
  hookSpecificOutput?: UserPromptExpansionHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseUserPromptExpansionInput(data: Record<string, any>): UserPromptExpansionInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    expansionType: data["expansion_type"],
    commandName: data["command_name"],
    prompt: data["prompt"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    commandArgs: data["command_args"] ?? undefined,
    commandSource: data["command_source"] ?? undefined,
  };
}

export function parseUserPromptExpansionHookSpecificOutput(data: Record<string, any>): UserPromptExpansionHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    additionalContext: data["additionalContext"] ?? undefined,
  };
}

export function parseUserPromptExpansionOutput(data: Record<string, any>): UserPromptExpansionOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    decision: data["decision"] ?? undefined,
    reason: data["reason"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parseUserPromptExpansionHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeUserPromptExpansionInput(obj: UserPromptExpansionInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["expansion_type"] = obj.expansionType;
  result["command_name"] = obj.commandName;
  result["prompt"] = obj.prompt;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.commandArgs !== undefined) {
    result["command_args"] = obj.commandArgs;
  }
  if (obj.commandSource !== undefined) {
    result["command_source"] = obj.commandSource;
  }
  return result;
}

export function serializeUserPromptExpansionHookSpecificOutput(obj: UserPromptExpansionHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  return result;
}

export function serializeUserPromptExpansionOutput(obj: UserPromptExpansionOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.decision !== undefined) {
    result["decision"] = obj.decision;
  }
  if (obj.reason !== undefined) {
    result["reason"] = obj.reason;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializeUserPromptExpansionHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: UserPromptExpansionInput) => UserPromptExpansionOutput | null): void {
  const event = parseUserPromptExpansionInput(JSON.parse(readStdin()));
  // Blocking event. Set decision="block" and reason to stop the action. Returning null allows.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeUserPromptExpansionOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
