// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.206 (2026-07-10). Re-scaffold when Claude Code is upgraded.
// Event: PostToolUse. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface PostToolUseInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Name of the tool that completed. */
  toolName: string;
  /** Arguments sent to the tool. */
  toolInput: Record<string, unknown>;
  /** Result returned by the tool. Object for built-in tools; content-block array for MCP tools. */
  toolResponse: Record<string, unknown> | Record<string, unknown>[];
  /** Unique identifier for this tool call. */
  toolUseId: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
  /** Tool execution time in milliseconds. Excludes time in permission prompts and PreToolUse hooks. */
  durationMs?: number;
}

export interface PostToolUseHookSpecificOutput {
  hookEventName: "PostToolUse";
  /** String added to Claude's context alongside the tool result. */
  additionalContext?: string;
  /** Replaces the tool's output with the provided value before it is sent to Claude. Must match the tool's output shape. */
  updatedToolOutput?: Record<string, unknown>;
  /** Replaces the output for MCP tools only. Prefer updatedToolOutput. */
  updatedMCPToolOutput?: Record<string, unknown>;
}

export interface PostToolUseOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  /** block adds the reason next to the tool result. Claude still sees the original output. */
  decision?: "block";
  /** Explanation shown to Claude when decision is block. */
  reason?: string;
  hookSpecificOutput?: PostToolUseHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parsePostToolUseInput(data: Record<string, any>): PostToolUseInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    toolName: data["tool_name"],
    toolInput: data["tool_input"],
    toolResponse: data["tool_response"],
    toolUseId: data["tool_use_id"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
    durationMs: data["duration_ms"] ?? undefined,
  };
}

export function parsePostToolUseHookSpecificOutput(data: Record<string, any>): PostToolUseHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    additionalContext: data["additionalContext"] ?? undefined,
    updatedToolOutput: data["updatedToolOutput"] ?? undefined,
    updatedMCPToolOutput: data["updatedMCPToolOutput"] ?? undefined,
  };
}

export function parsePostToolUseOutput(data: Record<string, any>): PostToolUseOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    decision: data["decision"] ?? undefined,
    reason: data["reason"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parsePostToolUseHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializePostToolUseInput(obj: PostToolUseInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["tool_name"] = obj.toolName;
  result["tool_input"] = obj.toolInput;
  result["tool_response"] = obj.toolResponse;
  result["tool_use_id"] = obj.toolUseId;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.durationMs !== undefined) {
    result["duration_ms"] = obj.durationMs;
  }
  return result;
}

export function serializePostToolUseHookSpecificOutput(obj: PostToolUseHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  if (obj.updatedToolOutput !== undefined) {
    result["updatedToolOutput"] = obj.updatedToolOutput;
  }
  if (obj.updatedMCPToolOutput !== undefined) {
    result["updatedMCPToolOutput"] = obj.updatedMCPToolOutput;
  }
  return result;
}

export function serializePostToolUseOutput(obj: PostToolUseOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.decision !== undefined) {
    result["decision"] = obj.decision;
  }
  if (obj.reason !== undefined) {
    result["reason"] = obj.reason;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializePostToolUseHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: PostToolUseInput) => PostToolUseOutput | null): void {
  const event = parsePostToolUseInput(JSON.parse(readStdin()));
  // Blocking event. Set decision="block" and reason to stop the action. Returning null allows.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializePostToolUseOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
