// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.185 (2026-06-20). Re-scaffold when Claude Code is upgraded.
// Event: TaskCompleted. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface TaskCompletedInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Identifier of the task being completed. */
  taskId: string;
  /** Title of the task. */
  taskSubject: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** Detailed description of the task. */
  taskDescription?: string;
  /** Name of the teammate completing the task. */
  teammateName?: string;
  /** Name of the team. */
  teamName?: string;
}

export interface TaskCompletedOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseTaskCompletedInput(data: Record<string, any>): TaskCompletedInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    taskId: data["task_id"],
    taskSubject: data["task_subject"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    taskDescription: data["task_description"] ?? undefined,
    teammateName: data["teammate_name"] ?? undefined,
    teamName: data["team_name"] ?? undefined,
  };
}

export function parseTaskCompletedOutput(data: Record<string, any>): TaskCompletedOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeTaskCompletedInput(obj: TaskCompletedInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["task_id"] = obj.taskId;
  result["task_subject"] = obj.taskSubject;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.taskDescription !== undefined) {
    result["task_description"] = obj.taskDescription;
  }
  if (obj.teammateName !== undefined) {
    result["teammate_name"] = obj.teammateName;
  }
  if (obj.teamName !== undefined) {
    result["team_name"] = obj.teamName;
  }
  return result;
}

export function serializeTaskCompletedOutput(obj: TaskCompletedOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  return result;
}

export function run(handle: (event: TaskCompletedInput) => TaskCompletedOutput | null): void {
  const event = parseTaskCompletedInput(JSON.parse(readStdin()));
  // Blocking event. Set continue=false to stop (or write a reason to stderr and process.exit(2)).
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeTaskCompletedOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
