# Generated by cc-flyrig from the Claude Code statusline IR — do not edit.
# Source schema: cc-2.1.201 (2026-07-04). Re-scaffold when Claude Code is upgraded.
# Event: SubagentStatusLine. Wire this package into settings.json yourself.

import json
import sys
from dataclasses import dataclass


@dataclass(slots=True)
class TaskInfo:
    """One entry of subagentStatusLine's tasks[]."""

    id: str
    type: str
    """Observed value: local_agent."""
    status: str
    """Observed value: running."""
    description: str
    label: str
    start_time: int
    """Epoch milliseconds."""
    token_count: int
    token_samples: list[int]
    cwd: str
    name: str | None = None
    """Documented by the /statusline reference."""

    @classmethod
    def from_dict(cls, data: dict) -> "TaskInfo":
        return cls(
            id=data["id"],
            type=data["type"],
            status=data["status"],
            description=data["description"],
            label=data["label"],
            start_time=data["startTime"],
            token_count=data["tokenCount"],
            token_samples=data["tokenSamples"],
            cwd=data["cwd"],
            name=data.get("name"),
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = self.id
        result["type"] = self.type
        result["status"] = self.status
        result["description"] = self.description
        result["label"] = self.label
        result["startTime"] = self.start_time
        result["tokenCount"] = self.token_count
        result["tokenSamples"] = self.token_samples
        result["cwd"] = self.cwd
        if self.name is not None:
            result["name"] = self.name
        return result


@dataclass(slots=True)
class SubagentStatusLineInput:
    """A small, fixed envelope — NOT a subset of StatusLineInput and NOT the hooks CommonInput envelope (no hook_event_name, no permission_mode)."""

    session_id: str
    transcript_path: str
    cwd: str
    prompt_id: str
    columns: int
    tasks: list[TaskInfo]

    @classmethod
    def from_dict(cls, data: dict) -> "SubagentStatusLineInput":
        return cls(
            session_id=data["session_id"],
            transcript_path=data["transcript_path"],
            cwd=data["cwd"],
            prompt_id=data["prompt_id"],
            columns=data["columns"],
            tasks=[TaskInfo.from_dict(_v) for _v in data["tasks"]],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["session_id"] = self.session_id
        result["transcript_path"] = self.transcript_path
        result["cwd"] = self.cwd
        result["prompt_id"] = self.prompt_id
        result["columns"] = self.columns
        result["tasks"] = [_v.to_dict() for _v in self.tasks]
        return result


@dataclass(slots=True)
class SubagentStatusLineOutput:
    """One {id, content} row per visible subagent. Authored from the /statusline reference."""

    id: str
    """Identifier of the subagent row this content replaces."""
    content: str
    """Text rendered for this subagent's row."""

    @classmethod
    def from_dict(cls, data: dict) -> "SubagentStatusLineOutput":
        return cls(
            id=data["id"],
            content=data["content"],
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = self.id
        result["content"] = self.content
        return result


def run(handle) -> int:
    """Read the hook event from stdin, call handle(), and write any decision to stdout.

    Returns 0. handle() may call sys.exit(2) to signal a denial via exit code instead of JSON.
    """
    event = SubagentStatusLineInput.from_dict(json.loads(sys.stdin.read()))
    # subagentStatusLine: one SubagentStatusLineOutput row per visible subagent, one JSON object per line.
    rows = handle(event)
    for row in rows:
        print(json.dumps(row.to_dict()))
    return 0
