// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.206 (2026-07-10). Re-scaffold when Claude Code is upgraded.
// Event: PreToolUse. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface PreToolUseInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Name of the tool being called. */
  toolName: string;
  /** Tool input parameters. Shape depends on the tool. */
  toolInput: Record<string, unknown>;
  /** Unique identifier for this tool call. */
  toolUseId: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
}

export interface PreToolUseHookSpecificOutput {
  hookEventName: "PreToolUse";
  /** allow skips the permission prompt. deny prevents the tool call. ask prompts the user. defer exits gracefully for later resumption. */
  permissionDecision?: "allow" | "deny" | "ask" | "defer";
  /** For allow and ask: shown to the user. For deny: shown to Claude. */
  permissionDecisionReason?: string;
  /** Modifies the tool's input parameters before execution. Replaces the entire input object. */
  updatedInput?: Record<string, unknown>;
  /** String added to Claude's context alongside the tool result. */
  additionalContext?: string;
}

export interface PreToolUseOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  hookSpecificOutput?: PreToolUseHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parsePreToolUseInput(data: Record<string, any>): PreToolUseInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    toolName: data["tool_name"],
    toolInput: data["tool_input"],
    toolUseId: data["tool_use_id"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
  };
}

export function parsePreToolUseHookSpecificOutput(data: Record<string, any>): PreToolUseHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    permissionDecision: data["permissionDecision"] ?? undefined,
    permissionDecisionReason: data["permissionDecisionReason"] ?? undefined,
    updatedInput: data["updatedInput"] ?? undefined,
    additionalContext: data["additionalContext"] ?? undefined,
  };
}

export function parsePreToolUseOutput(data: Record<string, any>): PreToolUseOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parsePreToolUseHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializePreToolUseInput(obj: PreToolUseInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["tool_name"] = obj.toolName;
  result["tool_input"] = obj.toolInput;
  result["tool_use_id"] = obj.toolUseId;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  return result;
}

export function serializePreToolUseHookSpecificOutput(obj: PreToolUseHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.permissionDecision !== undefined) {
    result["permissionDecision"] = obj.permissionDecision;
  }
  if (obj.permissionDecisionReason !== undefined) {
    result["permissionDecisionReason"] = obj.permissionDecisionReason;
  }
  if (obj.updatedInput !== undefined) {
    result["updatedInput"] = obj.updatedInput;
  }
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  return result;
}

export function serializePreToolUseOutput(obj: PreToolUseOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializePreToolUseHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: PreToolUseInput) => PreToolUseOutput | null): void {
  const event = parsePreToolUseInput(JSON.parse(readStdin()));
  // Blocking event. Exit 0 with JSON whose hookSpecificOutput.permissionDecision is one of
  // allow / deny / ask / defer. To deny via exit code instead, write a reason to stderr and
  // process.exit(2). Returning null takes no action and lets other hooks / the default decide.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializePreToolUseOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
