// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.201 (2026-07-04). Re-scaffold when Claude Code is upgraded.
// Event: PostToolBatch. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface ToolCallEntry {
  toolName: string;
  toolInput: Record<string, unknown>;
  toolUseId: string;
  /** The serialized tool_result content the model sees. A string or content-block array. */
  toolResponse: string | Record<string, unknown>[];
}

export interface PostToolBatchInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Every tool call in the batch. */
  toolCalls: ToolCallEntry[];
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
}

export interface PostToolBatchHookSpecificOutput {
  hookEventName: "PostToolBatch";
  /** Context string injected once before the next model call. */
  additionalContext?: string;
}

export interface PostToolBatchOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  /** block stops the agentic loop before the next model call. */
  decision?: "block";
  reason?: string;
  hookSpecificOutput?: PostToolBatchHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseToolCallEntry(data: Record<string, any>): ToolCallEntry {
  return {
    toolName: data["tool_name"],
    toolInput: data["tool_input"],
    toolUseId: data["tool_use_id"],
    toolResponse: data["tool_response"],
  };
}

export function parsePostToolBatchInput(data: Record<string, any>): PostToolBatchInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    toolCalls: data["tool_calls"].map(parseToolCallEntry),
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
  };
}

export function parsePostToolBatchHookSpecificOutput(data: Record<string, any>): PostToolBatchHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    additionalContext: data["additionalContext"] ?? undefined,
  };
}

export function parsePostToolBatchOutput(data: Record<string, any>): PostToolBatchOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    decision: data["decision"] ?? undefined,
    reason: data["reason"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parsePostToolBatchHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeToolCallEntry(obj: ToolCallEntry): Record<string, any> {
  const result: Record<string, any> = {};
  result["tool_name"] = obj.toolName;
  result["tool_input"] = obj.toolInput;
  result["tool_use_id"] = obj.toolUseId;
  result["tool_response"] = obj.toolResponse;
  return result;
}

export function serializePostToolBatchInput(obj: PostToolBatchInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["tool_calls"] = obj.toolCalls.map(serializeToolCallEntry);
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  return result;
}

export function serializePostToolBatchHookSpecificOutput(obj: PostToolBatchHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  return result;
}

export function serializePostToolBatchOutput(obj: PostToolBatchOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.decision !== undefined) {
    result["decision"] = obj.decision;
  }
  if (obj.reason !== undefined) {
    result["reason"] = obj.reason;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializePostToolBatchHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: PostToolBatchInput) => PostToolBatchOutput | null): void {
  const event = parsePostToolBatchInput(JSON.parse(readStdin()));
  // Blocking event. Set decision="block" and reason to stop the action. Returning null allows.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializePostToolBatchOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
