// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.185 (2026-06-20). Re-scaffold when Claude Code is upgraded.
// Event: MessageDisplay. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface MessageDisplayInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** UUID of the current turn. */
  turnId: string;
  /** UUID of the assistant message being displayed. Stable across every batch of the same message. */
  messageId: string;
  /** Zero-based index of this batch within the message. */
  index: number;
  /** true on the message's last batch. Each message has exactly one final batch. */
  final: boolean;
  /** The newly completed lines since the prior batch. Always whole lines except the final batch. */
  delta: string;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
}

export interface MessageDisplayHookSpecificOutput {
  hookEventName: "MessageDisplay";
  /** Text displayed in place of the delta. Omit to display the original. */
  displayContent?: string;
}

export interface MessageDisplayOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  hookSpecificOutput?: MessageDisplayHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseMessageDisplayInput(data: Record<string, any>): MessageDisplayInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    turnId: data["turn_id"],
    messageId: data["message_id"],
    index: data["index"],
    final: data["final"],
    delta: data["delta"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
  };
}

export function parseMessageDisplayHookSpecificOutput(data: Record<string, any>): MessageDisplayHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    displayContent: data["displayContent"] ?? undefined,
  };
}

export function parseMessageDisplayOutput(data: Record<string, any>): MessageDisplayOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parseMessageDisplayHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeMessageDisplayInput(obj: MessageDisplayInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["turn_id"] = obj.turnId;
  result["message_id"] = obj.messageId;
  result["index"] = obj.index;
  result["final"] = obj.final;
  result["delta"] = obj.delta;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  return result;
}

export function serializeMessageDisplayHookSpecificOutput(obj: MessageDisplayHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.displayContent !== undefined) {
    result["displayContent"] = obj.displayContent;
  }
  return result;
}

export function serializeMessageDisplayOutput(obj: MessageDisplayOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializeMessageDisplayHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: MessageDisplayInput) => MessageDisplayOutput | null): void {
  const event = parseMessageDisplayInput(JSON.parse(readStdin()));
  // Non-blocking event. Set hookSpecificOutput.displayContent to override what is shown.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeMessageDisplayOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
