// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.201 (2026-07-04). Re-scaffold when Claude Code is upgraded.
// Event: SessionStart. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface SessionStartInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** How the session was initiated. */
  source: "startup" | "resume" | "clear" | "compact";
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
  /** Model identifier. Only SessionStart hooks receive this field. Absent on the --init-only launch path. */
  model?: string;
  /** Current session title if one is already set. */
  sessionTitle?: string;
}

export interface SessionStartHookSpecificOutput {
  hookEventName: "SessionStart";
  /** String added to Claude's context at the start of the conversation. */
  additionalContext?: string;
  /** String used as the first user message of the session. Applies in non-interactive mode (-p). */
  initialUserMessage?: string;
  /** Sets the session title. Applies only when source is startup or resume. */
  sessionTitle?: string;
  /** Array of absolute paths to watch for FileChanged events during this session. */
  watchPaths?: string[];
  /** When true, Claude Code re-scans the skill and command directories after SessionStart hooks complete. */
  reloadSkills?: boolean;
}

export interface SessionStartOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  hookSpecificOutput?: SessionStartHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parseSessionStartInput(data: Record<string, any>): SessionStartInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    source: data["source"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
    model: data["model"] ?? undefined,
    sessionTitle: data["session_title"] ?? undefined,
  };
}

export function parseSessionStartHookSpecificOutput(data: Record<string, any>): SessionStartHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    additionalContext: data["additionalContext"] ?? undefined,
    initialUserMessage: data["initialUserMessage"] ?? undefined,
    sessionTitle: data["sessionTitle"] ?? undefined,
    watchPaths: data["watchPaths"] ?? undefined,
    reloadSkills: data["reloadSkills"] ?? undefined,
  };
}

export function parseSessionStartOutput(data: Record<string, any>): SessionStartOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parseSessionStartHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializeSessionStartInput(obj: SessionStartInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["source"] = obj.source;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.model !== undefined) {
    result["model"] = obj.model;
  }
  if (obj.sessionTitle !== undefined) {
    result["session_title"] = obj.sessionTitle;
  }
  return result;
}

export function serializeSessionStartHookSpecificOutput(obj: SessionStartHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.additionalContext !== undefined) {
    result["additionalContext"] = obj.additionalContext;
  }
  if (obj.initialUserMessage !== undefined) {
    result["initialUserMessage"] = obj.initialUserMessage;
  }
  if (obj.sessionTitle !== undefined) {
    result["sessionTitle"] = obj.sessionTitle;
  }
  if (obj.watchPaths !== undefined) {
    result["watchPaths"] = obj.watchPaths;
  }
  if (obj.reloadSkills !== undefined) {
    result["reloadSkills"] = obj.reloadSkills;
  }
  return result;
}

export function serializeSessionStartOutput(obj: SessionStartOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializeSessionStartHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: SessionStartInput) => SessionStartOutput | null): void {
  const event = parseSessionStartInput(JSON.parse(readStdin()));
  // Non-blocking event. Set hookSpecificOutput fields to inject context. Returning null is a no-op.
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializeSessionStartOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
