// Generated by cc-flyrig from the Claude Code hooks IR — do not edit.
// Source schema: cc-2.1.201 (2026-07-04). Re-scaffold when Claude Code is upgraded.
// Event: PermissionRequest. Wire this package into settings.json yourself.

import { readFileSync } from "node:fs";

export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

export interface EffortObject {
  level: EffortLevel;
}

export type PermissionMode = "default" | "plan" | "acceptEdits" | "auto" | "dontAsk" | "bypassPermissions";

export interface PermissionUpdateEntry {
  type: "addRules" | "replaceRules" | "removeRules" | "setMode" | "addDirectories" | "removeDirectories";
  destination: "session" | "localSettings" | "projectSettings" | "userSettings";
  /** For addRules/replaceRules/removeRules. */
  rules?: Record<string, unknown>[];
  /** For addRules/replaceRules/removeRules. */
  behavior?: "allow" | "deny" | "ask";
  /** For setMode. */
  mode?: "default" | "auto" | "acceptEdits" | "dontAsk" | "bypassPermissions" | "plan";
  /** For addDirectories/removeDirectories. */
  directories?: string[];
}

export interface PermissionRequestInput {
  /** Current session identifier. */
  sessionId: string;
  /** Path to conversation JSON. */
  transcriptPath: string;
  /** Current working directory when the hook is invoked. */
  cwd: string;
  /** Name of the event that fired. */
  hookEventName: string;
  /** Name of the tool requesting permission. */
  toolName: string;
  /** Tool input parameters. Shape depends on the tool. */
  toolInput: Record<string, unknown>;
  /** Current permission mode. Not all events include this field. */
  permissionMode?: PermissionMode;
  /** Active effort level for the turn. Present for events that fire within a tool-use context when the current model supports the effort parameter. */
  effort?: EffortObject;
  /** Unique identifier for the subagent. Present only when the hook fires inside a subagent call. */
  agentId?: string;
  /** Agent name. Present when the session uses --agent or the hook fires inside a subagent. */
  agentType?: string;
  /** UUID identifying the user prompt (turn) currently being processed. Matches the prompt.id attribute on OpenTelemetry events, so hook output can be correlated with telemetry for a single prompt. Absent until the first user input (e.g. session lifecycle events before any prompt). Requires Claude Code v2.1.196 or later. */
  promptId?: string;
  /** The always-allow options the user would normally see in the permission dialog. */
  permissionSuggestions?: PermissionUpdateEntry[];
}

export interface PermissionRequestHookSpecificDecision {
  /** allow grants the permission, deny denies it. */
  behavior: "allow" | "deny";
  /** For allow only: modifies the tool's input parameters before execution. */
  updatedInput?: Record<string, unknown>;
  /** For allow only: permission update entries to apply. */
  updatedPermissions?: PermissionUpdateEntry[];
  /** For deny only: tells Claude why the permission was denied. */
  message?: string;
  /** For deny only: if true, stops Claude. */
  interrupt?: boolean;
}

export interface PermissionRequestHookSpecificOutput {
  hookEventName: "PermissionRequest";
  decision?: PermissionRequestHookSpecificDecision;
}

export interface PermissionRequestOutput {
  /** If false, Claude stops processing entirely after the hook runs. */
  continue?: boolean;
  /** Message shown to the user when continue is false. Not shown to Claude. */
  stopReason?: string;
  /** If true, hides the hook's stdout from the transcript. */
  suppressOutput?: boolean;
  /** Warning message shown to the user. */
  systemMessage?: string;
  /** One or more terminal escape sequences for Claude Code to emit through its own terminal write path (race-free, works inside tmux/screen and on Windows). Each sequence must be terminated with BEL (\u0007) or ST (ESC \\). Multiple sequences may be concatenated into a single string. Allowed: OSC 0/1/2 (window and icon title), OSC 9 (iTerm2, ConEmu, WezTerm, Windows Terminal notifications; OSC 9;4 sets taskbar progress), OSC 99 (Kitty notifications), OSC 777 (urxvt, Ghostty, Warp notifications), bare BEL. Anything outside this allowlist — CSI cursor/color sequences, OSC 8 hyperlinks, OSC 52 clipboard writes, OSC 1337, OSC palette sequences — is rejected and the entire field is ignored. */
  terminalSequence?: string;
  hookSpecificOutput?: PermissionRequestHookSpecificOutput;
}

export function parseEffortObject(data: Record<string, any>): EffortObject {
  return {
    level: data["level"],
  };
}

export function parsePermissionUpdateEntry(data: Record<string, any>): PermissionUpdateEntry {
  return {
    type: data["type"],
    destination: data["destination"],
    rules: data["rules"] ?? undefined,
    behavior: data["behavior"] ?? undefined,
    mode: data["mode"] ?? undefined,
    directories: data["directories"] ?? undefined,
  };
}

export function parsePermissionRequestInput(data: Record<string, any>): PermissionRequestInput {
  return {
    sessionId: data["session_id"],
    transcriptPath: data["transcript_path"],
    cwd: data["cwd"],
    hookEventName: data["hook_event_name"],
    toolName: data["tool_name"],
    toolInput: data["tool_input"],
    permissionMode: data["permission_mode"] ?? undefined,
    effort: data["effort"] != null ? parseEffortObject(data["effort"]) : undefined,
    agentId: data["agent_id"] ?? undefined,
    agentType: data["agent_type"] ?? undefined,
    promptId: data["prompt_id"] ?? undefined,
    permissionSuggestions: data["permission_suggestions"] != null ? data["permission_suggestions"].map(parsePermissionUpdateEntry) : undefined,
  };
}

export function parsePermissionRequestHookSpecificDecision(data: Record<string, any>): PermissionRequestHookSpecificDecision {
  return {
    behavior: data["behavior"],
    updatedInput: data["updatedInput"] ?? undefined,
    updatedPermissions: data["updatedPermissions"] != null ? data["updatedPermissions"].map(parsePermissionUpdateEntry) : undefined,
    message: data["message"] ?? undefined,
    interrupt: data["interrupt"] ?? undefined,
  };
}

export function parsePermissionRequestHookSpecificOutput(data: Record<string, any>): PermissionRequestHookSpecificOutput {
  return {
    hookEventName: data["hookEventName"],
    decision: data["decision"] != null ? parsePermissionRequestHookSpecificDecision(data["decision"]) : undefined,
  };
}

export function parsePermissionRequestOutput(data: Record<string, any>): PermissionRequestOutput {
  return {
    continue: data["continue"] ?? undefined,
    stopReason: data["stopReason"] ?? undefined,
    suppressOutput: data["suppressOutput"] ?? undefined,
    systemMessage: data["systemMessage"] ?? undefined,
    terminalSequence: data["terminalSequence"] ?? undefined,
    hookSpecificOutput: data["hookSpecificOutput"] != null ? parsePermissionRequestHookSpecificOutput(data["hookSpecificOutput"]) : undefined,
  };
}

export function serializeEffortObject(obj: EffortObject): Record<string, any> {
  const result: Record<string, any> = {};
  result["level"] = obj.level;
  return result;
}

export function serializePermissionUpdateEntry(obj: PermissionUpdateEntry): Record<string, any> {
  const result: Record<string, any> = {};
  result["type"] = obj.type;
  result["destination"] = obj.destination;
  if (obj.rules !== undefined) {
    result["rules"] = obj.rules;
  }
  if (obj.behavior !== undefined) {
    result["behavior"] = obj.behavior;
  }
  if (obj.mode !== undefined) {
    result["mode"] = obj.mode;
  }
  if (obj.directories !== undefined) {
    result["directories"] = obj.directories;
  }
  return result;
}

export function serializePermissionRequestInput(obj: PermissionRequestInput): Record<string, any> {
  const result: Record<string, any> = {};
  result["session_id"] = obj.sessionId;
  result["transcript_path"] = obj.transcriptPath;
  result["cwd"] = obj.cwd;
  result["hook_event_name"] = obj.hookEventName;
  result["tool_name"] = obj.toolName;
  result["tool_input"] = obj.toolInput;
  if (obj.permissionMode !== undefined) {
    result["permission_mode"] = obj.permissionMode;
  }
  if (obj.effort !== undefined) {
    result["effort"] = serializeEffortObject(obj.effort);
  }
  if (obj.agentId !== undefined) {
    result["agent_id"] = obj.agentId;
  }
  if (obj.agentType !== undefined) {
    result["agent_type"] = obj.agentType;
  }
  if (obj.promptId !== undefined) {
    result["prompt_id"] = obj.promptId;
  }
  if (obj.permissionSuggestions !== undefined) {
    result["permission_suggestions"] = obj.permissionSuggestions.map(serializePermissionUpdateEntry);
  }
  return result;
}

export function serializePermissionRequestHookSpecificDecision(obj: PermissionRequestHookSpecificDecision): Record<string, any> {
  const result: Record<string, any> = {};
  result["behavior"] = obj.behavior;
  if (obj.updatedInput !== undefined) {
    result["updatedInput"] = obj.updatedInput;
  }
  if (obj.updatedPermissions !== undefined) {
    result["updatedPermissions"] = obj.updatedPermissions.map(serializePermissionUpdateEntry);
  }
  if (obj.message !== undefined) {
    result["message"] = obj.message;
  }
  if (obj.interrupt !== undefined) {
    result["interrupt"] = obj.interrupt;
  }
  return result;
}

export function serializePermissionRequestHookSpecificOutput(obj: PermissionRequestHookSpecificOutput): Record<string, any> {
  const result: Record<string, any> = {};
  result["hookEventName"] = obj.hookEventName;
  if (obj.decision !== undefined) {
    result["decision"] = serializePermissionRequestHookSpecificDecision(obj.decision);
  }
  return result;
}

export function serializePermissionRequestOutput(obj: PermissionRequestOutput): Record<string, any> {
  const result: Record<string, any> = {};
  if (obj.continue !== undefined) {
    result["continue"] = obj.continue;
  }
  if (obj.stopReason !== undefined) {
    result["stopReason"] = obj.stopReason;
  }
  if (obj.suppressOutput !== undefined) {
    result["suppressOutput"] = obj.suppressOutput;
  }
  if (obj.systemMessage !== undefined) {
    result["systemMessage"] = obj.systemMessage;
  }
  if (obj.terminalSequence !== undefined) {
    result["terminalSequence"] = obj.terminalSequence;
  }
  if (obj.hookSpecificOutput !== undefined) {
    result["hookSpecificOutput"] = serializePermissionRequestHookSpecificOutput(obj.hookSpecificOutput);
  }
  return result;
}

export function run(handle: (event: PermissionRequestInput) => PermissionRequestOutput | null): void {
  const event = parsePermissionRequestInput(JSON.parse(readStdin()));
  // Blocking event. Set hookSpecificOutput.decision.behavior to "allow" or "deny".
  const decision = handle(event);
  if (decision !== null) {
    console.log(JSON.stringify(serializePermissionRequestOutput(decision)));
  }
}

function readStdin(): string {
  return readFileSync(0, "utf-8");
}
